apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.application.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}